## Importing Numpy Library 

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(np.array(my_list))

numpy.ndarray

## Convert as numpy array 

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

## Create a series of numbers as an array with step field

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## Create an array of zeros 

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Create an arrray of ones 

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Create an array of numbers of series which is evenly allocated as per the no of elements we want. 

    Evenly splitted as it will reach the destination by equal steps

In [22]:
np.linspace(0,12,11)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8, 12. ])

## Create a random number

In [23]:
np.random.randint(0,1000,(3,3))

array([[719, 978, 582],
       [976, 332, 338],
       [611, 277, 879]])

## Seed in Random Package of Numpy
     ~ It stores the pattern of the random number generated and return the same random number when we run it again and again

In [24]:
np.random.seed(100)

np.random.randint(0,100,10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [25]:
np.random.seed(101)

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
np.random.seed(100)

np.random.randint(0,100,10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

## Some usefull methods in Numpy array

### ~ argmax returns the index of max value in an array

In [64]:
np.random.seed(200)

arr = np.random.randint(0,100,10)

arr

array([26, 16, 68, 42, 55, 76, 79, 89, 14, 91])

In [78]:
arr.max()
print (arr.max())
arr.argmax()

91


9

In [80]:
arr.min()
print(arr.min())
arr.argmin()

14


8

In [68]:
arr.mean()

55.6

### Reshape  an array

In [82]:
arr.reshape(2,5)

array([[26, 16, 68, 42, 55],
       [76, 79, 89, 14, 91]])

In [86]:
mat = np.arange(0,100).reshape(10,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [90]:
mat[8,8]

88

In [92]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [97]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [99]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

### Masking on the Array (Matrix) 

In [102]:
mat > 10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [105]:
myf = mat > 10

In [107]:
mat[myf]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       96, 97, 98, 99])

In [108]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])