## importing libraries 

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))
data

array([[45, 45],
       [94, 83],
       [14, 67],
       [27, 88],
       [38, 90],
       [40, 12],
       [ 4, 69],
       [30, 15],
       [17, 90],
       [10, 79]])

### Using MinMaxScaler to minimize (scale) the value in the array 

In [4]:
scaler_model = MinMaxScaler()

In [5]:
scaler_model.fit(data)

/home/ns/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

### To train the model for scaling 

In [6]:
scaler_model.transform(data)

array([[0.45555556, 0.42307692],
       [1.        , 0.91025641],
       [0.11111111, 0.70512821],
       [0.25555556, 0.97435897],
       [0.37777778, 1.        ],
       [0.4       , 0.        ],
       [0.        , 0.73076923],
       [0.28888889, 0.03846154],
       [0.14444444, 1.        ],
       [0.06666667, 0.85897436]])

In [7]:
scaler_model.fit_transform(data)

/home/ns/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.45555556, 0.42307692],
       [1.        , 0.91025641],
       [0.11111111, 0.70512821],
       [0.25555556, 0.97435897],
       [0.37777778, 1.        ],
       [0.4       , 0.        ],
       [0.        , 0.73076923],
       [0.28888889, 0.03846154],
       [0.14444444, 1.        ],
       [0.06666667, 0.85897436]])

## Importing Pandas

In [8]:
import pandas as pd

In [9]:
mydata = np.random.randint(0,101,(50,4))

In [10]:
mydata

array([[ 71,  44,  80,  87],
       [ 32,   0,  30,  74],
       [ 66,  15,  39,  80],
       [ 53,  86,  40,  17],
       [ 27,  69,  11,  50],
       [ 46,  93,  76,  72],
       [ 54,  49,  41,  54],
       [ 94,   7,  52,  17],
       [ 89,  64,  83,  76],
       [ 98,  96,  69,  84],
       [ 38,  27,  80,  95],
       [ 92,   1,  35,  13],
       [ 38,  89,  42,  35],
       [  1,  85,  85,  44],
       [ 45,  54,  89,  37],
       [ 86,  53,  45,  27],
       [ 64,   5,  24,  77],
       [ 91,  42,  59,  94],
       [ 64,   2,  25,  81],
       [ 99,  17,  41,  10],
       [ 55,   9,  42,  80],
       [ 48,   7,  63,  91],
       [ 50,  95,  29,  17],
       [  9,   6,  88,  56],
       [ 35,  36,  29,  26],
       [ 86,  74,  98,  90],
       [ 68,  47,  16,   4],
       [ 72,  89,  78,  59],
       [ 69,  80,  26,  47],
       [ 65,  24,  21,  14],
       [ 17,  28,   6,  87],
       [ 26,  21,  58,  42],
       [ 67,  87,  82,  46],
       [ 11,  79,  16,  22],
       [ 93,  

In [11]:
df = pd.DataFrame(data = mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [12]:
df

f1   f2  f3  label
0   71   44  80     87
1   32    0  30     74
2   66   15  39     80
3   53   86  40     17
4   27   69  11     50
5   46   93  76     72
6   54   49  41     54
7   94    7  52     17
8   89   64  83     76
9   98   96  69     84
10  38   27  80     95
11  92    1  35     13
12  38   89  42     35
13   1   85  85     44
14  45   54  89     37
15  86   53  45     27
16  64    5  24     77
17  91   42  59     94
18  64    2  25     81
19  99   17  41     10
20  55    9  42     80
21  48    7  63     91
22  50   95  29     17
23   9    6  88     56
24  35   36  29     26
25  86   74  98     90
26  68   47  16      4
27  72   89  78     59
28  69   80  26     47
29  65   24  21     14
30  17   28   6     87
31  26   21  58     42
32  67   87  82     46
33  11   79  16     22
34  93   21  84     67
35  23   57  47     90
36  38   62  64     18
37   5   90  34      1
38  39   66  31     51
39  88   98  49     88
40  68   13  15     54
41  91   77   4     32
42  27   85  86     85
43  98   52  67     35
44  71   41  27     70
45  26   62  44     74
46  69  100  88     62
47  62   67  38     34
48  22    5  15      8
49  53   31  24     20

In [14]:
x = df[['f1', 'f2', 'f3']]

In [15]:
x

f1   f2  f3
0   71   44  80
1   32    0  30
2   66   15  39
3   53   86  40
4   27   69  11
5   46   93  76
6   54   49  41
7   94    7  52
8   89   64  83
9   98   96  69
10  38   27  80
11  92    1  35
12  38   89  42
13   1   85  85
14  45   54  89
15  86   53  45
16  64    5  24
17  91   42  59
18  64    2  25
19  99   17  41
20  55    9  42
21  48    7  63
22  50   95  29
23   9    6  88
24  35   36  29
25  86   74  98
26  68   47  16
27  72   89  78
28  69   80  26
29  65   24  21
30  17   28   6
31  26   21  58
32  67   87  82
33  11   79  16
34  93   21  84
35  23   57  47
36  38   62  64
37   5   90  34
38  39   66  31
39  88   98  49
40  68   13  15
41  91   77   4
42  27   85  86
43  98   52  67
44  71   41  27
45  26   62  44
46  69  100  88
47  62   67  38
48  22    5  15
49  53   31  24

In [16]:
y = df['label']

In [17]:
y

0     87
1     74
2     80
3     17
4     50
5     72
6     54
7     17
8     76
9     84
10    95
11    13
12    35
13    44
14    37
15    27
16    77
17    94
18    81
19    10
20    80
21    91
22    17
23    56
24    26
25    90
26     4
27    59
28    47
29    14
30    87
31    42
32    46
33    22
34    67
35    90
36    18
37     1
38    51
39    88
40    54
41    32
42    85
43    35
44    70
45    74
46    62
47    34
48     8
49    20
Name: label, dtype: int64

### Importing Train Test Split to split Test and Training data 

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)