## Importing libraries 

In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    
    result = sess.run(hello+world)

In [8]:
print (result)

b'Hello World'


In [9]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
type(a)
type(b)

tensorflow.python.framework.ops.Tensor

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4, 4), 10)

In [18]:
my_zeros = tf.zeros((4, 4))

In [19]:
my_ones = tf.ones((4, 4))

In [20]:
myrandn = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [21]:
myrandu = tf.random_uniform((4, 4), minval = 0, maxval = 1)

In [22]:
my_ops = [const, fill_mat, my_zeros, my_ones, myrandn, myrandu]

In [23]:
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print (sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1.4407288   2.0622368  -0.5728073  -1.2974968 ]
 [ 1.0315053   0.14175351  0.68645394 -1.5888261 ]
 [-0.54844254 -0.81133443  0.21930441 -2.6337469 ]
 [-1.1572561   1.2531645   0.3481718  -0.39660233]]
[[0.58138967 0.5673286  0.83512974 0.35809612]
 [0.36263275 0.6938548  0.27865326 0.7171687 ]
 [0.67713356 0.3311653  0.81336653 0.9995563 ]
 [0.11060691 0.58242786 0.9803908  0.65466654]]


In [25]:
demo_randn = tf.random_normal((1, 1), mean = 3, stddev = 0)
print (sess.run(demo_randn))

[[3.]]


In [26]:
demo_randu = tf.random_uniform((1, 1), minval=-1, maxval=2.2)
print (demo_randu.eval())

[[1.0085118]]


In [27]:
a = tf.constant([ [10, 20], 
                  [30, 40] ])

b = tf.constant([ [10], [20]])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a, b)

In [31]:
sess.run(result)

array([[ 500],
       [1100]], dtype=int32)

In [32]:
result.eval()

array([[ 500],
       [1100]], dtype=int32)