## Importing libraries 

In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    
    result = sess.run(hello+world)

In [8]:
print (result)

b'Hello World'


In [9]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
type(a)
type(b)

tensorflow.python.framework.ops.Tensor

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [33]:
fill_mat = tf.fill((4, 4), 10)
print (fill_mat)
fill_mat.eval()

Tensor("Fill_1:0", shape=(4, 4), dtype=int32)


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [18]:
my_zeros = tf.zeros((4, 4))

In [19]:
my_ones = tf.ones((4, 4))

In [20]:
myrandn = tf.random_normal((4, 4), mean = 0, stddev = 1.0)


In [21]:
myrandu = tf.random_uniform((4, 4), minval = 0, maxval = 1)

In [22]:
my_ops = [const, fill_mat, my_zeros, my_ones, myrandn, myrandu]

In [23]:
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print (sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.33657864  0.08675835 -1.991971   -0.20344661]
 [ 0.9635438   1.8004606   0.7069893  -0.10885791]
 [-0.00851612  0.09836083  0.40526927 -0.21830325]
 [ 1.3883802  -0.98641557  1.126984   -0.8904706 ]]
[[0.21285188 0.7035191  0.8396182  0.59534717]
 [0.7417247  0.6761205  0.41482592 0.00880682]
 [0.14954293 0.25292945 0.5417688  0.91606295]
 [0.45186424 0.9463694  0.6803521  0.24957407]]


In [25]:
demo_randn = tf.random_normal((1, 1), mean = 3, stddev = 0)
print (sess.run(demo_randn))

[[3.]]


In [26]:
demo_randu = tf.random_uniform((1, 1), minval=-1, maxval=2.2)
print (demo_randu.eval())

[[2.057092]]


In [27]:
a = tf.constant([ [10, 20], 
                  [30, 40] ])

b = tf.constant([ [10], [20]])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a, b)

In [31]:
sess.run(result)

array([[ 500],
       [1100]], dtype=int32)

In [32]:
result.eval()

array([[ 500],
       [1100]], dtype=int32)