## Importing libraries 

In [44]:
import tensorflow as tf

In [45]:
print (tf.__version__)

1.11.0


In [46]:
hello = tf.constant("Hello ")

In [47]:
world = tf.constant("World")

In [48]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [49]:
print(hello)

Tensor("Const_6:0", shape=(), dtype=string)


In [50]:
with tf.Session() as sess:
    
    result = sess.run(hello+world)

In [51]:
print (result)

b'Hello World'


In [52]:
a = tf.constant(10)
b = tf.constant(20)

In [53]:
type(a)
type(b)

tensorflow.python.framework.ops.Tensor

In [54]:
a + b

<tf.Tensor 'add_11:0' shape=() dtype=int32>

In [55]:
a + b

<tf.Tensor 'add_12:0' shape=() dtype=int32>

In [56]:
a + b

<tf.Tensor 'add_13:0' shape=() dtype=int32>

In [57]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [58]:
result

30

In [59]:
const = tf.constant(10)

In [60]:
fill_mat = tf.fill((4, 4), 10)

In [61]:
my_zeros = tf.zeros((4, 4))

In [62]:
my_ones = tf.ones((4, 4))

In [63]:
myrandn = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [66]:
myrandu = tf.random_uniform((4, 4), minval = 0, maxval = 1)

In [69]:
my_ops = [const, fill_mat, my_zeros, my_ones, myrandn, myrandu]

In [329]:
sess = tf.InteractiveSession()

/home/ns/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [330]:
for op in my_ops:
    print (sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 2.3545647  -0.58859384  0.34008205 -1.4645917 ]
 [ 0.6471345  -1.0845717   1.4047381   0.47005478]
 [-0.5544145  -0.7808153  -0.11394012 -0.12393147]
 [-1.0072836   0.46679977  0.22588457  0.256668  ]]
[[0.15868402 0.18079722 0.17880023 0.8684242 ]
 [0.8176569  0.60454845 0.40870857 0.8987758 ]
 [0.624768   0.331918   0.47892475 0.02715027]
 [0.55222046 0.02519727 0.9435078  0.19200695]]


In [331]:
demo_randn = tf.random_normal((1, 1), mean = 3, stddev = 0)
print (sess.run(demo_randn))

[[3.]]


In [397]:
demo_randu = tf.random_uniform((1, 1), minval=-1, maxval=2.2)
print (demo_randu.eval())

[[1.9709957]]
